### ISSUE TITLE
/trade on 可以增加一个整理按钮

### ISSUE THREAD

**Issue by Cat7373** [XJcraft/StockMarket#2]
一键合并同类型物品到一起，方便不需要看详细信息的玩家取回物品。

**Comment by reezhu** [comment]
其实可以加一个一键全收……不过怕有人背包满了放不进去

**Comment by Cat7373** [comment]
这个不难解决啊，背包满了就停止，不继续收了。。

**Comment by reezhu** [comment]
就怕循环耗资源……我先放着todo吧

**Comment by Cat7373** [comment]
我的半成品 Mod 自动合成台里就有类似的代码- -
不过那是 Mod 的做法。。。

**Comment by reezhu** [comment]
回头测试一下原生的give会是怎么个表现

**Comment by Cat7373** [comment]
妮想测试神马- -
窝看过Give的源码- -

**Comment by Cat7373** [comment]
从玩家背包遍历寻找跟目标物品可以堆叠 且还没满的位置 -> 没找到的话就找一个空白的位置 -> 给玩家物品
如果还没找到就停止循环
大概就是酱紫

**Comment by reezhu** [comment]
确实可以这样，不过每个格子都要遍历一遍不知道会不会卡，之后我自己试好了再做，现在的都是基本功能

**Comment by Cat7373** [comment]
在服务器上啊，所有数据都等于是在读内存，非常快的。。。

**Comment by reezhu** [comment]
那我下次把它实现了吧……

**Comment by Cat7373** [comment]
窝自己都忘了还有这么个Issue- -

**Comment by reezhu** [comment]
怎么标记为solved= =

**Comment by reezhu** [comment]
close！

**Comment by Cat7373** [comment]
只有Open跟Close两种状态啦- -
不过右边可以加标签之类的
